spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    url: jdbc:postgresql://dpg-xyz12345.render.com:5432/payphone_db
    username: payphone_db_user
    password: I4PkYRe9qqmG9mYbeOFhLl0rSWrNhVce
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect   # <- agrega esto
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    default-property-inclusion: non_null

server:
  port: 8015
  servlet:
    context-path: /cobros-payphone

logging:
  level:
    net.dualcorp.cobrospayphonews: DEBUG

seguridad:
  token:
    clave: miClaveSecretaParaJwtDePruebasToken
